package com.kunlun.erp.core.entity;

import java.util.Date;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_type
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer company_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String company_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.belong_platform
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer belong_platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.business_licence_url
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String business_licence_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.business_certificate
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String business_certificate;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.country_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer country_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.country_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String country_name;

    private Integer district_id;

    private String district_name;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.province_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer province_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.province_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String province_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.city_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.city_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.county_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer county_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.county_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String county_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.address
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.introduction
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.cooperation_state
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer cooperation_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.contact_person
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer contact_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.contract_document_state
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer contract_document_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.contract_document_url
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String contract_document_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.cooperation_start_date
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Date cooperation_start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.cooperation_end_date
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Date cooperation_end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.leader_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String leader_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.leader_mobile
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String leader_mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.leader_wechat
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String leader_wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.leader_address
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String leader_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.settlement_mode
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer settlement_mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.credit_level
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String credit_level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.is_common_use
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer is_common_use;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.remarks
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.create_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.update_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.creator_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer creator_id;
    /**
     * 创建人名字
     */
    private String creator_name;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public CompanyInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.id
     *
     * @return the value of company_info.id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.id
     *
     * @param id the value for company_info.id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_code
     *
     * @return the value of company_info.company_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_code
     *
     * @param company_code the value for company_info.company_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_type
     *
     * @return the value of company_info.company_type
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCompany_type() {
        return company_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_type
     *
     * @param company_type the value for company_info.company_type
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCompany_type(Integer company_type) {
        this.company_type = company_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_name
     *
     * @return the value of company_info.company_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_name
     *
     * @param company_name the value for company_info.company_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name == null ? null : company_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.belong_platform
     *
     * @return the value of company_info.belong_platform
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getBelong_platform() {
        return belong_platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.belong_platform
     *
     * @param belong_platform the value for company_info.belong_platform
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setBelong_platform(Integer belong_platform) {
        this.belong_platform = belong_platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.business_licence_url
     *
     * @return the value of company_info.business_licence_url
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getBusiness_licence_url() {
        return business_licence_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.business_licence_url
     *
     * @param business_licence_url the value for company_info.business_licence_url
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setBusiness_licence_url(String business_licence_url) {
        this.business_licence_url = business_licence_url == null ? null : business_licence_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.business_certificate
     *
     * @return the value of company_info.business_certificate
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getBusiness_certificate() {
        return business_certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.business_certificate
     *
     * @param business_certificate the value for company_info.business_certificate
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setBusiness_certificate(String business_certificate) {
        this.business_certificate = business_certificate == null ? null : business_certificate.trim();
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.country_id
     *
     * @return the value of company_info.country_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCountry_id() {
        return country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.country_id
     *
     * @param country_id the value for company_info.country_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCountry_id(Integer country_id) {
        this.country_id = country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.country_name
     *
     * @return the value of company_info.country_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCountry_name() {
        return country_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.country_name
     *
     * @param country_name the value for company_info.country_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCountry_name(String country_name) {
        this.country_name = country_name == null ? null : country_name.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.province_id
     *
     * @return the value of company_info.province_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getProvince_id() {
        return province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.province_id
     *
     * @param province_id the value for company_info.province_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.province_name
     *
     * @return the value of company_info.province_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getProvince_name() {
        return province_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.province_name
     *
     * @param province_name the value for company_info.province_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setProvince_name(String province_name) {
        this.province_name = province_name == null ? null : province_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.city_id
     *
     * @return the value of company_info.city_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.city_id
     *
     * @param city_id the value for company_info.city_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.city_name
     *
     * @return the value of company_info.city_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCity_name() {
        return city_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.city_name
     *
     * @param city_name the value for company_info.city_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCity_name(String city_name) {
        this.city_name = city_name == null ? null : city_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.county_id
     *
     * @return the value of company_info.county_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCounty_id() {
        return county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.county_id
     *
     * @param county_id the value for company_info.county_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCounty_id(Integer county_id) {
        this.county_id = county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.county_name
     *
     * @return the value of company_info.county_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCounty_name() {
        return county_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.county_name
     *
     * @param county_name the value for company_info.county_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCounty_name(String county_name) {
        this.county_name = county_name == null ? null : county_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.address
     *
     * @return the value of company_info.address
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.address
     *
     * @param address the value for company_info.address
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.introduction
     *
     * @return the value of company_info.introduction
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.introduction
     *
     * @param introduction the value for company_info.introduction
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.cooperation_state
     *
     * @return the value of company_info.cooperation_state
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCooperation_state() {
        return cooperation_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.cooperation_state
     *
     * @param cooperation_state the value for company_info.cooperation_state
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCooperation_state(Integer cooperation_state) {
        this.cooperation_state = cooperation_state;
    }

    public Integer getContact_person() {
        return contact_person;
    }

    public void setContact_person(Integer contact_person) {
        this.contact_person = contact_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.contract_document_state
     *
     * @return the value of company_info.contract_document_state
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getContract_document_state() {
        return contract_document_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.contract_document_state
     *
     * @param contract_document_state the value for company_info.contract_document_state
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setContract_document_state(Integer contract_document_state) {
        this.contract_document_state = contract_document_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.contract_document_url
     *
     * @return the value of company_info.contract_document_url
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getContract_document_url() {
        return contract_document_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.contract_document_url
     *
     * @param contract_document_url the value for company_info.contract_document_url
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setContract_document_url(String contract_document_url) {
        this.contract_document_url = contract_document_url == null ? null : contract_document_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.cooperation_start_date
     *
     * @return the value of company_info.cooperation_start_date
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Date getCooperation_start_date() {
        return cooperation_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.cooperation_start_date
     *
     * @param cooperation_start_date the value for company_info.cooperation_start_date
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCooperation_start_date(Date cooperation_start_date) {
        this.cooperation_start_date = cooperation_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.cooperation_end_date
     *
     * @return the value of company_info.cooperation_end_date
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Date getCooperation_end_date() {
        return cooperation_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.cooperation_end_date
     *
     * @param cooperation_end_date the value for company_info.cooperation_end_date
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCooperation_end_date(Date cooperation_end_date) {
        this.cooperation_end_date = cooperation_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.leader_name
     *
     * @return the value of company_info.leader_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getLeader_name() {
        return leader_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.leader_name
     *
     * @param leader_name the value for company_info.leader_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setLeader_name(String leader_name) {
        this.leader_name = leader_name == null ? null : leader_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.leader_mobile
     *
     * @return the value of company_info.leader_mobile
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getLeader_mobile() {
        return leader_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.leader_mobile
     *
     * @param leader_mobile the value for company_info.leader_mobile
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setLeader_mobile(String leader_mobile) {
        this.leader_mobile = leader_mobile == null ? null : leader_mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.leader_wechat
     *
     * @return the value of company_info.leader_wechat
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getLeader_wechat() {
        return leader_wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.leader_wechat
     *
     * @param leader_wechat the value for company_info.leader_wechat
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setLeader_wechat(String leader_wechat) {
        this.leader_wechat = leader_wechat == null ? null : leader_wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.leader_address
     *
     * @return the value of company_info.leader_address
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getLeader_address() {
        return leader_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.leader_address
     *
     * @param leader_address the value for company_info.leader_address
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setLeader_address(String leader_address) {
        this.leader_address = leader_address == null ? null : leader_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.settlement_mode
     *
     * @return the value of company_info.settlement_mode
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getSettlement_mode() {
        return settlement_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.settlement_mode
     *
     * @param settlement_mode the value for company_info.settlement_mode
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setSettlement_mode(Integer settlement_mode) {
        this.settlement_mode = settlement_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.credit_level
     *
     * @return the value of company_info.credit_level
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCredit_level() {
        return credit_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.credit_level
     *
     * @param credit_level the value for company_info.credit_level
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCredit_level(String credit_level) {
        this.credit_level = credit_level == null ? null : credit_level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.is_common_use
     *
     * @return the value of company_info.is_common_use
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getIs_common_use() {
        return is_common_use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.is_common_use
     *
     * @param is_common_use the value for company_info.is_common_use
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setIs_common_use(Integer is_common_use) {
        this.is_common_use = is_common_use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.remarks
     *
     * @return the value of company_info.remarks
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.remarks
     *
     * @param remarks the value for company_info.remarks
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.create_time
     *
     * @return the value of company_info.create_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.create_time
     *
     * @param create_time the value for company_info.create_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.update_time
     *
     * @return the value of company_info.update_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.update_time
     *
     * @param update_time the value for company_info.update_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.creator_id
     *
     * @return the value of company_info.creator_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.creator_id
     *
     * @param creator_id the value for company_info.creator_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }


    public String getCreator_name() {
        return creator_name;
    }

    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name;
    }

    public Integer getDistrict_id() {
        return district_id;
    }

    public void setDistrict_id(Integer district_id) {
        this.district_id = district_id;
    }

    public String getDistrict_name() {
        return district_name;
    }

    public void setDistrict_name(String district_name) {
        this.district_name = district_name;
    }
}