package com.kunlun.erp.core.entity;

import java.util.Date;

public class FinancialAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.id
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.company_code
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.account_code
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private String account_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.account_type
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private Integer account_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.account_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private String account_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.account_no
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private String account_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.bank_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private String bank_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.is_default
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private Integer is_default;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.create_time
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.creator_id
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_account.creator_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_account
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public FinancialAccount(Integer id, String company_code, String account_code, Integer account_type, String account_name, String account_no, String bank_name, Integer is_default, Date create_time, Integer creator_id, String creator_name) {
        this.id = id;
        this.company_code = company_code;
        this.account_code = account_code;
        this.account_type = account_type;
        this.account_name = account_name;
        this.account_no = account_no;
        this.bank_name = bank_name;
        this.is_default = is_default;
        this.create_time = create_time;
        this.creator_id = creator_id;
        this.creator_name = creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_account
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public FinancialAccount() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.id
     *
     * @return the value of financial_account.id
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.id
     *
     * @param id the value for financial_account.id
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.company_code
     *
     * @return the value of financial_account.company_code
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.company_code
     *
     * @param company_code the value for financial_account.company_code
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.account_code
     *
     * @return the value of financial_account.account_code
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public String getAccount_code() {
        return account_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.account_code
     *
     * @param account_code the value for financial_account.account_code
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setAccount_code(String account_code) {
        this.account_code = account_code == null ? null : account_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.account_type
     *
     * @return the value of financial_account.account_type
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public Integer getAccount_type() {
        return account_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.account_type
     *
     * @param account_type the value for financial_account.account_type
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setAccount_type(Integer account_type) {
        this.account_type = account_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.account_name
     *
     * @return the value of financial_account.account_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public String getAccount_name() {
        return account_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.account_name
     *
     * @param account_name the value for financial_account.account_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setAccount_name(String account_name) {
        this.account_name = account_name == null ? null : account_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.account_no
     *
     * @return the value of financial_account.account_no
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public String getAccount_no() {
        return account_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.account_no
     *
     * @param account_no the value for financial_account.account_no
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setAccount_no(String account_no) {
        this.account_no = account_no == null ? null : account_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.bank_name
     *
     * @return the value of financial_account.bank_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public String getBank_name() {
        return bank_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.bank_name
     *
     * @param bank_name the value for financial_account.bank_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setBank_name(String bank_name) {
        this.bank_name = bank_name == null ? null : bank_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.is_default
     *
     * @return the value of financial_account.is_default
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public Integer getIs_default() {
        return is_default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.is_default
     *
     * @param is_default the value for financial_account.is_default
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setIs_default(Integer is_default) {
        this.is_default = is_default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.create_time
     *
     * @return the value of financial_account.create_time
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.create_time
     *
     * @param create_time the value for financial_account.create_time
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.creator_id
     *
     * @return the value of financial_account.creator_id
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.creator_id
     *
     * @param creator_id the value for financial_account.creator_id
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_account.creator_name
     *
     * @return the value of financial_account.creator_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_account.creator_name
     *
     * @param creator_name the value for financial_account.creator_name
     *
     * @mbggenerated Mon Dec 02 15:41:15 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}