package com.kunlun.erp.core.entity;

import java.util.Date;

public class GroupCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.id
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.product_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private String product_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.route_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private String route_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.route_plan_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private String route_plan_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.price_plan_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private String price_plan_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.departrue_date
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private Date departrue_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.create_time
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.creator_id
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_code.creator_name
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.id
     *
     * @return the value of group_code.id
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.id
     *
     * @param id the value for group_code.id
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.product_code
     *
     * @return the value of group_code.product_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.product_code
     *
     * @param product_code the value for group_code.product_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.route_code
     *
     * @return the value of group_code.route_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public String getRoute_code() {
        return route_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.route_code
     *
     * @param route_code the value for group_code.route_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setRoute_code(String route_code) {
        this.route_code = route_code == null ? null : route_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.route_plan_code
     *
     * @return the value of group_code.route_plan_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public String getRoute_plan_code() {
        return route_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.route_plan_code
     *
     * @param route_plan_code the value for group_code.route_plan_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code == null ? null : route_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.price_plan_code
     *
     * @return the value of group_code.price_plan_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public String getPrice_plan_code() {
        return price_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.price_plan_code
     *
     * @param price_plan_code the value for group_code.price_plan_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setPrice_plan_code(String price_plan_code) {
        this.price_plan_code = price_plan_code == null ? null : price_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.departrue_date
     *
     * @return the value of group_code.departrue_date
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public Date getDepartrue_date() {
        return departrue_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.departrue_date
     *
     * @param departrue_date the value for group_code.departrue_date
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setDepartrue_date(Date departrue_date) {
        this.departrue_date = departrue_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.create_time
     *
     * @return the value of group_code.create_time
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.create_time
     *
     * @param create_time the value for group_code.create_time
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.creator_id
     *
     * @return the value of group_code.creator_id
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.creator_id
     *
     * @param creator_id the value for group_code.creator_id
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_code.creator_name
     *
     * @return the value of group_code.creator_name
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_code.creator_name
     *
     * @param creator_name the value for group_code.creator_name
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}