package com.kunlun.erp.core.entity;

import java.util.Date;

public class PersonInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.company_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_type
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer person_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String person_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_mobile
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String person_mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_wechat
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String person_wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_phone
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String person_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.person_qq
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String person_qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.position
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.remarks
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.create_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.update_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.creator_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    private Integer creator_id;

    private String creator_name;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public PersonInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.id
     *
     * @return the value of person_info.id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.id
     *
     * @param id the value for person_info.id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.company_code
     *
     * @return the value of person_info.company_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.company_code
     *
     * @param company_code the value for person_info.company_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_code
     *
     * @return the value of person_info.person_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_code
     *
     * @param person_code the value for person_info.person_code
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_type
     *
     * @return the value of person_info.person_type
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getPerson_type() {
        return person_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_type
     *
     * @param person_type the value for person_info.person_type
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_type(Integer person_type) {
        this.person_type = person_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_name
     *
     * @return the value of person_info.person_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPerson_name() {
        return person_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_name
     *
     * @param person_name the value for person_info.person_name
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_name(String person_name) {
        this.person_name = person_name == null ? null : person_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_mobile
     *
     * @return the value of person_info.person_mobile
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPerson_mobile() {
        return person_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_mobile
     *
     * @param person_mobile the value for person_info.person_mobile
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_mobile(String person_mobile) {
        this.person_mobile = person_mobile == null ? null : person_mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_wechat
     *
     * @return the value of person_info.person_wechat
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPerson_wechat() {
        return person_wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_wechat
     *
     * @param person_wechat the value for person_info.person_wechat
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_wechat(String person_wechat) {
        this.person_wechat = person_wechat == null ? null : person_wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_phone
     *
     * @return the value of person_info.person_phone
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPerson_phone() {
        return person_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_phone
     *
     * @param person_phone the value for person_info.person_phone
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_phone(String person_phone) {
        this.person_phone = person_phone == null ? null : person_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.person_qq
     *
     * @return the value of person_info.person_qq
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPerson_qq() {
        return person_qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.person_qq
     *
     * @param person_qq the value for person_info.person_qq
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPerson_qq(String person_qq) {
        this.person_qq = person_qq == null ? null : person_qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.position
     *
     * @return the value of person_info.position
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.position
     *
     * @param position the value for person_info.position
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.remarks
     *
     * @return the value of person_info.remarks
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.remarks
     *
     * @param remarks the value for person_info.remarks
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.create_time
     *
     * @return the value of person_info.create_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.create_time
     *
     * @param create_time the value for person_info.create_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.update_time
     *
     * @return the value of person_info.update_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.update_time
     *
     * @param update_time the value for person_info.update_time
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.creator_id
     *
     * @return the value of person_info.creator_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.creator_id
     *
     * @param creator_id the value for person_info.creator_id
     *
     * @mbggenerated Thu Nov 21 15:56:28 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    public String getCreator_name() {
        return creator_name;
    }

    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name;
    }
}