package com.kunlun.erp.core.entity;

import java.util.Date;

public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_code
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private String category_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_name
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private String category_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_name_defined
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private String category_name_defined;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_state
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private Integer category_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.create_time
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.update_time
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.creator_id
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.creator_name
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_code
     *
     * @return the value of product_category.category_code
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public String getCategory_code() {
        return category_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_code
     *
     * @param category_code the value for product_category.category_code
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCategory_code(String category_code) {
        this.category_code = category_code == null ? null : category_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_name
     *
     * @return the value of product_category.category_name
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public String getCategory_name() {
        return category_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_name
     *
     * @param category_name the value for product_category.category_name
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCategory_name(String category_name) {
        this.category_name = category_name == null ? null : category_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_name_defined
     *
     * @return the value of product_category.category_name_defined
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public String getCategory_name_defined() {
        return category_name_defined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_name_defined
     *
     * @param category_name_defined the value for product_category.category_name_defined
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCategory_name_defined(String category_name_defined) {
        this.category_name_defined = category_name_defined == null ? null : category_name_defined.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_state
     *
     * @return the value of product_category.category_state
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public Integer getCategory_state() {
        return category_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_state
     *
     * @param category_state the value for product_category.category_state
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCategory_state(Integer category_state) {
        this.category_state = category_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.create_time
     *
     * @return the value of product_category.create_time
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.create_time
     *
     * @param create_time the value for product_category.create_time
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.update_time
     *
     * @return the value of product_category.update_time
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.update_time
     *
     * @param update_time the value for product_category.update_time
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.creator_id
     *
     * @return the value of product_category.creator_id
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.creator_id
     *
     * @param creator_id the value for product_category.creator_id
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.creator_name
     *
     * @return the value of product_category.creator_name
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.creator_name
     *
     * @param creator_name the value for product_category.creator_name
     *
     * @mbggenerated Thu Dec 05 09:20:44 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}