package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RoutePricePlanDetail {

    private Integer id;

    private String price_code;

    private String product_code;

    private String route_code;

    private String route_plan_code;

    private String price_plan_code;

    private Date departure_date;

    private BigDecimal adult_trade_price;

    private BigDecimal children_trade_price;

    private BigDecimal adult_sales_price;

    private BigDecimal children_sales_price;

    private BigDecimal room_diff_price;

    private Integer inventory;

    private BigDecimal cost_price;

    private Date create_time;

    private Date update_time;

    private Integer creator_id;

    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.id
     *
     * @return the value of route_price_plan_detail.id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.id
     *
     * @param id the value for route_price_plan_detail.id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.price_code
     *
     * @return the value of route_price_plan_detail.price_code
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public String getPrice_code() {
        return price_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.price_code
     *
     * @param price_code the value for route_price_plan_detail.price_code
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setPrice_code(String price_code) {
        this.price_code = price_code == null ? null : price_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.price_plan_code
     *
     * @return the value of route_price_plan_detail.price_plan_code
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public String getPrice_plan_code() {
        return price_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.price_plan_code
     *
     * @param price_plan_code the value for route_price_plan_detail.price_plan_code
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setPrice_plan_code(String price_plan_code) {
        this.price_plan_code = price_plan_code == null ? null : price_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.departure_date
     *
     * @return the value of route_price_plan_detail.departure_date
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Date getDeparture_date() {
        return departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.departure_date
     *
     * @param departure_date the value for route_price_plan_detail.departure_date
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setDeparture_date(Date departure_date) {
        this.departure_date = departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.adult_trade_price
     *
     * @return the value of route_price_plan_detail.adult_trade_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public BigDecimal getAdult_trade_price() {
        return adult_trade_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.adult_trade_price
     *
     * @param adult_trade_price the value for route_price_plan_detail.adult_trade_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setAdult_trade_price(BigDecimal adult_trade_price) {
        this.adult_trade_price = adult_trade_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.children_trade_price
     *
     * @return the value of route_price_plan_detail.children_trade_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public BigDecimal getChildren_trade_price() {
        return children_trade_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.children_trade_price
     *
     * @param children_trade_price the value for route_price_plan_detail.children_trade_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setChildren_trade_price(BigDecimal children_trade_price) {
        this.children_trade_price = children_trade_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.adult_sales_price
     *
     * @return the value of route_price_plan_detail.adult_sales_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public BigDecimal getAdult_sales_price() {
        return adult_sales_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.adult_sales_price
     *
     * @param adult_sales_price the value for route_price_plan_detail.adult_sales_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setAdult_sales_price(BigDecimal adult_sales_price) {
        this.adult_sales_price = adult_sales_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.children_sales_price
     *
     * @return the value of route_price_plan_detail.children_sales_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public BigDecimal getChildren_sales_price() {
        return children_sales_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.children_sales_price
     *
     * @param children_sales_price the value for route_price_plan_detail.children_sales_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setChildren_sales_price(BigDecimal children_sales_price) {
        this.children_sales_price = children_sales_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.room_diff_price
     *
     * @return the value of route_price_plan_detail.room_diff_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public BigDecimal getRoom_diff_price() {
        return room_diff_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.room_diff_price
     *
     * @param room_diff_price the value for route_price_plan_detail.room_diff_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setRoom_diff_price(BigDecimal room_diff_price) {
        this.room_diff_price = room_diff_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.inventory
     *
     * @return the value of route_price_plan_detail.inventory
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.inventory
     *
     * @param inventory the value for route_price_plan_detail.inventory
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.cost_price
     *
     * @return the value of route_price_plan_detail.cost_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public BigDecimal getCost_price() {
        return cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.cost_price
     *
     * @param cost_price the value for route_price_plan_detail.cost_price
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCost_price(BigDecimal cost_price) {
        this.cost_price = cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.create_time
     *
     * @return the value of route_price_plan_detail.create_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.create_time
     *
     * @param create_time the value for route_price_plan_detail.create_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.update_time
     *
     * @return the value of route_price_plan_detail.update_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.update_time
     *
     * @param update_time the value for route_price_plan_detail.update_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.creator_id
     *
     * @return the value of route_price_plan_detail.creator_id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.creator_id
     *
     * @param creator_id the value for route_price_plan_detail.creator_id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_detail.creator_name
     *
     * @return the value of route_price_plan_detail.creator_name
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_detail.creator_name
     *
     * @param creator_name the value for route_price_plan_detail.creator_name
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }

    public String getProduct_code() {
        return product_code;
    }

    public void setProduct_code(String product_code) {
        this.product_code = product_code;
    }

    public String getRoute_code() {
        return route_code;
    }

    public void setRoute_code(String route_code) {
        this.route_code = route_code;
    }

    public String getRoute_plan_code() {
        return route_plan_code;
    }

    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code;
    }
}