package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteReside {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.id
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.reside_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String reside_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.group_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.company_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.person_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.room_type
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Integer room_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.start_date
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Date start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.end_date
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Date end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.days
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.currency
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.fee
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.room_count
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Integer room_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.fee_total
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private BigDecimal fee_total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.remarks
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.create_time
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.update_time
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.creator_id
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_reside.creator_name
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.id
     *
     * @return the value of route_reside.id
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.id
     *
     * @param id the value for route_reside.id
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.reside_code
     *
     * @return the value of route_reside.reside_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getReside_code() {
        return reside_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.reside_code
     *
     * @param reside_code the value for route_reside.reside_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setReside_code(String reside_code) {
        this.reside_code = reside_code == null ? null : reside_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.group_code
     *
     * @return the value of route_reside.group_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.group_code
     *
     * @param group_code the value for route_reside.group_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.company_code
     *
     * @return the value of route_reside.company_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.company_code
     *
     * @param company_code the value for route_reside.company_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.person_code
     *
     * @return the value of route_reside.person_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.person_code
     *
     * @param person_code the value for route_reside.person_code
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.room_type
     *
     * @return the value of route_reside.room_type
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Integer getRoom_type() {
        return room_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.room_type
     *
     * @param room_type the value for route_reside.room_type
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setRoom_type(Integer room_type) {
        this.room_type = room_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.start_date
     *
     * @return the value of route_reside.start_date
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Date getStart_date() {
        return start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.start_date
     *
     * @param start_date the value for route_reside.start_date
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.end_date
     *
     * @return the value of route_reside.end_date
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Date getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.end_date
     *
     * @param end_date the value for route_reside.end_date
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setEnd_date(Date end_date) {
        this.end_date = end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.days
     *
     * @return the value of route_reside.days
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.days
     *
     * @param days the value for route_reside.days
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.currency
     *
     * @return the value of route_reside.currency
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.currency
     *
     * @param currency the value for route_reside.currency
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.fee
     *
     * @return the value of route_reside.fee
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.fee
     *
     * @param fee the value for route_reside.fee
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.room_count
     *
     * @return the value of route_reside.room_count
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Integer getRoom_count() {
        return room_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.room_count
     *
     * @param room_count the value for route_reside.room_count
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setRoom_count(Integer room_count) {
        this.room_count = room_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.fee_total
     *
     * @return the value of route_reside.fee_total
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public BigDecimal getFee_total() {
        return fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.fee_total
     *
     * @param fee_total the value for route_reside.fee_total
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setFee_total(BigDecimal fee_total) {
        this.fee_total = fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.remarks
     *
     * @return the value of route_reside.remarks
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.remarks
     *
     * @param remarks the value for route_reside.remarks
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.create_time
     *
     * @return the value of route_reside.create_time
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.create_time
     *
     * @param create_time the value for route_reside.create_time
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.update_time
     *
     * @return the value of route_reside.update_time
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.update_time
     *
     * @param update_time the value for route_reside.update_time
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.creator_id
     *
     * @return the value of route_reside.creator_id
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.creator_id
     *
     * @param creator_id the value for route_reside.creator_id
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_reside.creator_name
     *
     * @return the value of route_reside.creator_name
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_reside.creator_name
     *
     * @param creator_name the value for route_reside.creator_name
     *
     * @mbggenerated Fri Dec 20 16:08:59 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}