package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteGuides {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.id
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.guide_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String guide_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.group_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.company_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.person_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.client_count
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Integer client_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.start_date
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Date start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.end_date
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Date end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.days
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.currency
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.fee_daily
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private BigDecimal fee_daily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.fee_total
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private BigDecimal fee_total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.remarks
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.create_times
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Date create_times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.update_time
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.creator_id
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_guides.creator_name
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.id
     *
     * @return the value of route_guides.id
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.id
     *
     * @param id the value for route_guides.id
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.guide_code
     *
     * @return the value of route_guides.guide_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getGuide_code() {
        return guide_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.guide_code
     *
     * @param guide_code the value for route_guides.guide_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setGuide_code(String guide_code) {
        this.guide_code = guide_code == null ? null : guide_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.group_code
     *
     * @return the value of route_guides.group_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.group_code
     *
     * @param group_code the value for route_guides.group_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.company_code
     *
     * @return the value of route_guides.company_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.company_code
     *
     * @param company_code the value for route_guides.company_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.person_code
     *
     * @return the value of route_guides.person_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.person_code
     *
     * @param person_code the value for route_guides.person_code
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.client_count
     *
     * @return the value of route_guides.client_count
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Integer getClient_count() {
        return client_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.client_count
     *
     * @param client_count the value for route_guides.client_count
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setClient_count(Integer client_count) {
        this.client_count = client_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.start_date
     *
     * @return the value of route_guides.start_date
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Date getStart_date() {
        return start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.start_date
     *
     * @param start_date the value for route_guides.start_date
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.end_date
     *
     * @return the value of route_guides.end_date
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Date getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.end_date
     *
     * @param end_date the value for route_guides.end_date
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setEnd_date(Date end_date) {
        this.end_date = end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.days
     *
     * @return the value of route_guides.days
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.days
     *
     * @param days the value for route_guides.days
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.currency
     *
     * @return the value of route_guides.currency
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.currency
     *
     * @param currency the value for route_guides.currency
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.fee_daily
     *
     * @return the value of route_guides.fee_daily
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public BigDecimal getFee_daily() {
        return fee_daily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.fee_daily
     *
     * @param fee_daily the value for route_guides.fee_daily
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setFee_daily(BigDecimal fee_daily) {
        this.fee_daily = fee_daily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.fee_total
     *
     * @return the value of route_guides.fee_total
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public BigDecimal getFee_total() {
        return fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.fee_total
     *
     * @param fee_total the value for route_guides.fee_total
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setFee_total(BigDecimal fee_total) {
        this.fee_total = fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.remarks
     *
     * @return the value of route_guides.remarks
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.remarks
     *
     * @param remarks the value for route_guides.remarks
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.create_times
     *
     * @return the value of route_guides.create_times
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Date getCreate_times() {
        return create_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.create_times
     *
     * @param create_times the value for route_guides.create_times
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setCreate_times(Date create_times) {
        this.create_times = create_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.update_time
     *
     * @return the value of route_guides.update_time
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.update_time
     *
     * @param update_time the value for route_guides.update_time
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.creator_id
     *
     * @return the value of route_guides.creator_id
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.creator_id
     *
     * @param creator_id the value for route_guides.creator_id
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_guides.creator_name
     *
     * @return the value of route_guides.creator_name
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_guides.creator_name
     *
     * @param creator_name the value for route_guides.creator_name
     *
     * @mbggenerated Thu Dec 19 17:34:09 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}