package com.kunlun.erp.core.entity;

import java.util.Date;

public class RouteHall {

    private Integer id;

    private String product_code;

    private String internal_code;

    private String route_plan_code;

    private String price_plan_code;

    private String group_code;

    private Date departure_date;

    private Date disband_date;

    private String product_name;

    private Integer count_plan;

    private Integer count_confirm;

    private Integer count_hold;

    private Integer count_remain;

    private Integer status;

    private Integer approve_state;

    private String approve_remarks;

    private Date approve_time;

    private Integer approve_id;

    private String approve_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_hall.create_time
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_hall.update_time
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_hall.creator_id
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_hall.creator_name
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.id
     *
     * @return the value of route_hall.id
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.id
     *
     * @param id the value for route_hall.id
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.product_code
     *
     * @return the value of route_hall.product_code
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.product_code
     *
     * @param product_code the value for route_hall.product_code
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.internal_code
     *
     * @return the value of route_hall.internal_code
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public String getInternal_code() {
        return internal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.internal_code
     *
     * @param internal_code the value for route_hall.internal_code
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setInternal_code(String internal_code) {
        this.internal_code = internal_code == null ? null : internal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.route_plan_code
     *
     * @return the value of route_hall.route_plan_code
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public String getRoute_plan_code() {
        return route_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.route_plan_code
     *
     * @param route_plan_code the value for route_hall.route_plan_code
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code == null ? null : route_plan_code.trim();
    }


    public String getGroup_code() {
        return group_code;
    }

    public void setGroup_code(String group_code) {
        this.group_code = group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.departure_date
     *
     * @return the value of route_hall.departure_date
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Date getDeparture_date() {
        return departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.departure_date
     *
     * @param departure_date the value for route_hall.departure_date
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setDeparture_date(Date departure_date) {
        this.departure_date = departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.disband_date
     *
     * @return the value of route_hall.disband_date
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Date getDisband_date() {
        return disband_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.disband_date
     *
     * @param disband_date the value for route_hall.disband_date
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setDisband_date(Date disband_date) {
        this.disband_date = disband_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.product_name
     *
     * @return the value of route_hall.product_name
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public String getProduct_name() {
        return product_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.product_name
     *
     * @param product_name the value for route_hall.product_name
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setProduct_name(String product_name) {
        this.product_name = product_name == null ? null : product_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.count_plan
     *
     * @return the value of route_hall.count_plan
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getCount_plan() {
        return count_plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.count_plan
     *
     * @param count_plan the value for route_hall.count_plan
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCount_plan(Integer count_plan) {
        this.count_plan = count_plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.count_confirm
     *
     * @return the value of route_hall.count_confirm
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getCount_confirm() {
        return count_confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.count_confirm
     *
     * @param count_confirm the value for route_hall.count_confirm
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCount_confirm(Integer count_confirm) {
        this.count_confirm = count_confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.count_hold
     *
     * @return the value of route_hall.count_hold
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getCount_hold() {
        return count_hold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.count_hold
     *
     * @param count_hold the value for route_hall.count_hold
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCount_hold(Integer count_hold) {
        this.count_hold = count_hold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.count_remain
     *
     * @return the value of route_hall.count_remain
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getCount_remain() {
        return count_remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.count_remain
     *
     * @param count_remain the value for route_hall.count_remain
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCount_remain(Integer count_remain) {
        this.count_remain = count_remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.status
     *
     * @return the value of route_hall.status
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.status
     *
     * @param status the value for route_hall.status
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.create_time
     *
     * @return the value of route_hall.create_time
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.create_time
     *
     * @param create_time the value for route_hall.create_time
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.update_time
     *
     * @return the value of route_hall.update_time
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.update_time
     *
     * @param update_time the value for route_hall.update_time
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.creator_id
     *
     * @return the value of route_hall.creator_id
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.creator_id
     *
     * @param creator_id the value for route_hall.creator_id
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_hall.creator_name
     *
     * @return the value of route_hall.creator_name
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_hall.creator_name
     *
     * @param creator_name the value for route_hall.creator_name
     *
     * @mbggenerated Wed Dec 18 09:48:45 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }

    public String getPrice_plan_code() {
        return price_plan_code;
    }

    public void setPrice_plan_code(String price_plan_code) {
        this.price_plan_code = price_plan_code;
    }

    public Integer getApprove_state() {
        return approve_state;
    }

    public void setApprove_state(Integer approve_state) {
        this.approve_state = approve_state;
    }

    public String getApprove_remarks() {
        return approve_remarks;
    }

    public void setApprove_remarks(String approve_remarks) {
        this.approve_remarks = approve_remarks;
    }

    public Date getApprove_time() {
        return approve_time;
    }

    public void setApprove_time(Date approve_time) {
        this.approve_time = approve_time;
    }

    public Integer getApprove_id() {
        return approve_id;
    }

    public void setApprove_id(Integer approve_id) {
        this.approve_id = approve_id;
    }

    public String getApprove_name() {
        return approve_name;
    }

    public void setApprove_name(String approve_name) {
        this.approve_name = approve_name;
    }
}