package com.kunlun.erp.core.entity;

import java.util.Date;

public class RouteInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.id
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.product_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private String product_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.route_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private String route_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.internal_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private String internal_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.is_shopping
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private Integer is_shopping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.owner_expense
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private Integer owner_expense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.room_type
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private String room_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.insurance_type
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private String insurance_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.create_time
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.update_time
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.creator_id
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_info.creator_name
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.id
     *
     * @return the value of route_info.id
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.id
     *
     * @param id the value for route_info.id
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.product_code
     *
     * @return the value of route_info.product_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.product_code
     *
     * @param product_code the value for route_info.product_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.route_code
     *
     * @return the value of route_info.route_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public String getRoute_code() {
        return route_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.route_code
     *
     * @param route_code the value for route_info.route_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setRoute_code(String route_code) {
        this.route_code = route_code == null ? null : route_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.internal_code
     *
     * @return the value of route_info.internal_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public String getInternal_code() {
        return internal_code==null?"":internal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.internal_code
     *
     * @param internal_code the value for route_info.internal_code
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setInternal_code(String internal_code) {
        this.internal_code = internal_code == null ? null : internal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.is_shopping
     *
     * @return the value of route_info.is_shopping
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public Integer getIs_shopping() {
        return is_shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.is_shopping
     *
     * @param is_shopping the value for route_info.is_shopping
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setIs_shopping(Integer is_shopping) {
        this.is_shopping = is_shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.owner_expense
     *
     * @return the value of route_info.owner_expense
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public Integer getOwner_expense() {
        return owner_expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.owner_expense
     *
     * @param owner_expense the value for route_info.owner_expense
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setOwner_expense(Integer owner_expense) {
        this.owner_expense = owner_expense;
    }

    public String getRoom_type() {
        return room_type;
    }

    public void setRoom_type(String room_type) {
        this.room_type = room_type;
    }

    public String getInsurance_type() {
        return insurance_type;
    }

    public void setInsurance_type(String insurance_type) {
        this.insurance_type = insurance_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.create_time
     *
     * @return the value of route_info.create_time
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.create_time
     *
     * @param create_time the value for route_info.create_time
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.update_time
     *
     * @return the value of route_info.update_time
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.update_time
     *
     * @param update_time the value for route_info.update_time
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.creator_id
     *
     * @return the value of route_info.creator_id
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.creator_id
     *
     * @param creator_id the value for route_info.creator_id
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_info.creator_name
     *
     * @return the value of route_info.creator_name
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_info.creator_name
     *
     * @param creator_name the value for route_info.creator_name
     *
     * @mbggenerated Sat Dec 07 13:31:14 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}