package com.kunlun.erp.core.entity;

import java.util.Date;

public class RouteTravelAgency {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.id
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.travel_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private String travel_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.group_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.company_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.person_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.remarks
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.create_time
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.update_time
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.creator_id
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency.creator_name
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.id
     *
     * @return the value of route_travel_agency.id
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.id
     *
     * @param id the value for route_travel_agency.id
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.travel_code
     *
     * @return the value of route_travel_agency.travel_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public String getTravel_code() {
        return travel_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.travel_code
     *
     * @param travel_code the value for route_travel_agency.travel_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setTravel_code(String travel_code) {
        this.travel_code = travel_code == null ? null : travel_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.group_code
     *
     * @return the value of route_travel_agency.group_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.group_code
     *
     * @param group_code the value for route_travel_agency.group_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.company_code
     *
     * @return the value of route_travel_agency.company_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.company_code
     *
     * @param company_code the value for route_travel_agency.company_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.person_code
     *
     * @return the value of route_travel_agency.person_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.person_code
     *
     * @param person_code the value for route_travel_agency.person_code
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.remarks
     *
     * @return the value of route_travel_agency.remarks
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.remarks
     *
     * @param remarks the value for route_travel_agency.remarks
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.create_time
     *
     * @return the value of route_travel_agency.create_time
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.create_time
     *
     * @param create_time the value for route_travel_agency.create_time
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.update_time
     *
     * @return the value of route_travel_agency.update_time
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.update_time
     *
     * @param update_time the value for route_travel_agency.update_time
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.creator_id
     *
     * @return the value of route_travel_agency.creator_id
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.creator_id
     *
     * @param creator_id the value for route_travel_agency.creator_id
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency.creator_name
     *
     * @return the value of route_travel_agency.creator_name
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency.creator_name
     *
     * @param creator_name the value for route_travel_agency.creator_name
     *
     * @mbggenerated Wed Dec 25 11:31:44 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}