package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteTraffic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.id
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.traffic_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String traffic_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.group_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.company_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.traffic_type
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Integer traffic_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.departure_date
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Date departure_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.departure
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String departure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.destination
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.currency
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.fee
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.traffic_count
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Integer traffic_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.fee_total
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private BigDecimal fee_total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.remarks
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.create_time
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.update_time
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.creator_id
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_traffic.creator_name
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.id
     *
     * @return the value of route_traffic.id
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.id
     *
     * @param id the value for route_traffic.id
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.traffic_code
     *
     * @return the value of route_traffic.traffic_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getTraffic_code() {
        return traffic_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.traffic_code
     *
     * @param traffic_code the value for route_traffic.traffic_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setTraffic_code(String traffic_code) {
        this.traffic_code = traffic_code == null ? null : traffic_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.group_code
     *
     * @return the value of route_traffic.group_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.group_code
     *
     * @param group_code the value for route_traffic.group_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.company_code
     *
     * @return the value of route_traffic.company_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.company_code
     *
     * @param company_code the value for route_traffic.company_code
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.traffic_type
     *
     * @return the value of route_traffic.traffic_type
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Integer getTraffic_type() {
        return traffic_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.traffic_type
     *
     * @param traffic_type the value for route_traffic.traffic_type
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setTraffic_type(Integer traffic_type) {
        this.traffic_type = traffic_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.departure_date
     *
     * @return the value of route_traffic.departure_date
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Date getDeparture_date() {
        return departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.departure_date
     *
     * @param departure_date the value for route_traffic.departure_date
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setDeparture_date(Date departure_date) {
        this.departure_date = departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.departure
     *
     * @return the value of route_traffic.departure
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.departure
     *
     * @param departure the value for route_traffic.departure
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setDeparture(String departure) {
        this.departure = departure == null ? null : departure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.destination
     *
     * @return the value of route_traffic.destination
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.destination
     *
     * @param destination the value for route_traffic.destination
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.currency
     *
     * @return the value of route_traffic.currency
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.currency
     *
     * @param currency the value for route_traffic.currency
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.fee
     *
     * @return the value of route_traffic.fee
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.fee
     *
     * @param fee the value for route_traffic.fee
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.traffic_count
     *
     * @return the value of route_traffic.traffic_count
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Integer getTraffic_count() {
        return traffic_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.traffic_count
     *
     * @param traffic_count the value for route_traffic.traffic_count
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setTraffic_count(Integer traffic_count) {
        this.traffic_count = traffic_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.fee_total
     *
     * @return the value of route_traffic.fee_total
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public BigDecimal getFee_total() {
        return fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.fee_total
     *
     * @param fee_total the value for route_traffic.fee_total
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setFee_total(BigDecimal fee_total) {
        this.fee_total = fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.remarks
     *
     * @return the value of route_traffic.remarks
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.remarks
     *
     * @param remarks the value for route_traffic.remarks
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.create_time
     *
     * @return the value of route_traffic.create_time
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.create_time
     *
     * @param create_time the value for route_traffic.create_time
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.update_time
     *
     * @return the value of route_traffic.update_time
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.update_time
     *
     * @param update_time the value for route_traffic.update_time
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.creator_id
     *
     * @return the value of route_traffic.creator_id
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.creator_id
     *
     * @param creator_id the value for route_traffic.creator_id
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_traffic.creator_name
     *
     * @return the value of route_traffic.creator_name
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_traffic.creator_name
     *
     * @param creator_name the value for route_traffic.creator_name
     *
     * @mbggenerated Tue Dec 24 20:45:31 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}