package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteTravelAgencyIncome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.id
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.income_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private String income_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.group_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.company_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.fee_type
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private Integer fee_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.fee_description
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private String fee_description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.currency
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.price
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.quantity
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.total_price
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private BigDecimal total_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.create_time
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.update_time
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.creator_id
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_travel_agency_income.creator_name
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.id
     *
     * @return the value of route_travel_agency_income.id
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.id
     *
     * @param id the value for route_travel_agency_income.id
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.income_code
     *
     * @return the value of route_travel_agency_income.income_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public String getIncome_code() {
        return income_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.income_code
     *
     * @param income_code the value for route_travel_agency_income.income_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setIncome_code(String income_code) {
        this.income_code = income_code == null ? null : income_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.group_code
     *
     * @return the value of route_travel_agency_income.group_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.group_code
     *
     * @param group_code the value for route_travel_agency_income.group_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.company_code
     *
     * @return the value of route_travel_agency_income.company_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.company_code
     *
     * @param company_code the value for route_travel_agency_income.company_code
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.fee_type
     *
     * @return the value of route_travel_agency_income.fee_type
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public Integer getFee_type() {
        return fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.fee_type
     *
     * @param fee_type the value for route_travel_agency_income.fee_type
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setFee_type(Integer fee_type) {
        this.fee_type = fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.fee_description
     *
     * @return the value of route_travel_agency_income.fee_description
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public String getFee_description() {
        return fee_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.fee_description
     *
     * @param fee_description the value for route_travel_agency_income.fee_description
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setFee_description(String fee_description) {
        this.fee_description = fee_description == null ? null : fee_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.currency
     *
     * @return the value of route_travel_agency_income.currency
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.currency
     *
     * @param currency the value for route_travel_agency_income.currency
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.price
     *
     * @return the value of route_travel_agency_income.price
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.price
     *
     * @param price the value for route_travel_agency_income.price
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.quantity
     *
     * @return the value of route_travel_agency_income.quantity
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.quantity
     *
     * @param quantity the value for route_travel_agency_income.quantity
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.total_price
     *
     * @return the value of route_travel_agency_income.total_price
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public BigDecimal getTotal_price() {
        return total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.total_price
     *
     * @param total_price the value for route_travel_agency_income.total_price
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setTotal_price(BigDecimal total_price) {
        this.total_price = total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.create_time
     *
     * @return the value of route_travel_agency_income.create_time
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.create_time
     *
     * @param create_time the value for route_travel_agency_income.create_time
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.update_time
     *
     * @return the value of route_travel_agency_income.update_time
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.update_time
     *
     * @param update_time the value for route_travel_agency_income.update_time
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.creator_id
     *
     * @return the value of route_travel_agency_income.creator_id
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.creator_id
     *
     * @param creator_id the value for route_travel_agency_income.creator_id
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_travel_agency_income.creator_name
     *
     * @return the value of route_travel_agency_income.creator_name
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_travel_agency_income.creator_name
     *
     * @param creator_name the value for route_travel_agency_income.creator_name
     *
     * @mbggenerated Thu Dec 26 14:51:06 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}