package com.kunlun.erp.core.entity;

import java.util.Date;

public class RouteOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.order_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String order_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.group_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.product_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String product_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.route_plan_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String route_plan_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.price_plan_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String price_plan_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.company_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.contact_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String contact_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.company_order_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String company_order_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_country_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer client_country_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_country_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String client_country_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_district_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer client_district_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_district_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String client_district_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_province_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer client_province_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_province_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String client_province_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_city_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer client_city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_city_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String client_city_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_county_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer client_county_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.client_county_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String client_county_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.hotel_level
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer hotel_level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.room_standard_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer room_standard_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.room_big_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer room_big_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.room_three_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer room_three_count;

    private Integer accompany_room_count;

    private Integer no_room_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.adult_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer adult_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.children_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer children_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.state
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.remarks
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.create_time
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.update_time
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.creator_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_order.creator_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.id
     *
     * @return the value of route_order.id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.id
     *
     * @param id the value for route_order.id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.order_code
     *
     * @return the value of route_order.order_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getOrder_code() {
        return order_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.order_code
     *
     * @param order_code the value for route_order.order_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setOrder_code(String order_code) {
        this.order_code = order_code == null ? null : order_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.group_code
     *
     * @return the value of route_order.group_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.group_code
     *
     * @param group_code the value for route_order.group_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.product_code
     *
     * @return the value of route_order.product_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.product_code
     *
     * @param product_code the value for route_order.product_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.route_plan_code
     *
     * @return the value of route_order.route_plan_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getRoute_plan_code() {
        return route_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.route_plan_code
     *
     * @param route_plan_code the value for route_order.route_plan_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code == null ? null : route_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.price_plan_code
     *
     * @return the value of route_order.price_plan_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getPrice_plan_code() {
        return price_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.price_plan_code
     *
     * @param price_plan_code the value for route_order.price_plan_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setPrice_plan_code(String price_plan_code) {
        this.price_plan_code = price_plan_code == null ? null : price_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.company_code
     *
     * @return the value of route_order.company_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.company_code
     *
     * @param company_code the value for route_order.company_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.contact_code
     *
     * @return the value of route_order.contact_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getContact_code() {
        return contact_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.contact_code
     *
     * @param contact_code the value for route_order.contact_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setContact_code(String contact_code) {
        this.contact_code = contact_code == null ? null : contact_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.company_order_code
     *
     * @return the value of route_order.company_order_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getCompany_order_code() {
        return company_order_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.company_order_code
     *
     * @param company_order_code the value for route_order.company_order_code
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setCompany_order_code(String company_order_code) {
        this.company_order_code = company_order_code == null ? null : company_order_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_country_id
     *
     * @return the value of route_order.client_country_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getClient_country_id() {
        return client_country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_country_id
     *
     * @param client_country_id the value for route_order.client_country_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_country_id(Integer client_country_id) {
        this.client_country_id = client_country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_country_name
     *
     * @return the value of route_order.client_country_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getClient_country_name() {
        return client_country_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_country_name
     *
     * @param client_country_name the value for route_order.client_country_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_country_name(String client_country_name) {
        this.client_country_name = client_country_name == null ? null : client_country_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_district_id
     *
     * @return the value of route_order.client_district_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getClient_district_id() {
        return client_district_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_district_id
     *
     * @param client_district_id the value for route_order.client_district_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_district_id(Integer client_district_id) {
        this.client_district_id = client_district_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_district_name
     *
     * @return the value of route_order.client_district_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getClient_district_name() {
        return client_district_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_district_name
     *
     * @param client_district_name the value for route_order.client_district_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_district_name(String client_district_name) {
        this.client_district_name = client_district_name == null ? null : client_district_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_province_id
     *
     * @return the value of route_order.client_province_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getClient_province_id() {
        return client_province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_province_id
     *
     * @param client_province_id the value for route_order.client_province_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_province_id(Integer client_province_id) {
        this.client_province_id = client_province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_province_name
     *
     * @return the value of route_order.client_province_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getClient_province_name() {
        return client_province_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_province_name
     *
     * @param client_province_name the value for route_order.client_province_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_province_name(String client_province_name) {
        this.client_province_name = client_province_name == null ? null : client_province_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_city_id
     *
     * @return the value of route_order.client_city_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getClient_city_id() {
        return client_city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_city_id
     *
     * @param client_city_id the value for route_order.client_city_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_city_id(Integer client_city_id) {
        this.client_city_id = client_city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_city_name
     *
     * @return the value of route_order.client_city_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getClient_city_name() {
        return client_city_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_city_name
     *
     * @param client_city_name the value for route_order.client_city_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_city_name(String client_city_name) {
        this.client_city_name = client_city_name == null ? null : client_city_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_county_id
     *
     * @return the value of route_order.client_county_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getClient_county_id() {
        return client_county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_county_id
     *
     * @param client_county_id the value for route_order.client_county_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_county_id(Integer client_county_id) {
        this.client_county_id = client_county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.client_county_name
     *
     * @return the value of route_order.client_county_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getClient_county_name() {
        return client_county_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.client_county_name
     *
     * @param client_county_name the value for route_order.client_county_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setClient_county_name(String client_county_name) {
        this.client_county_name = client_county_name == null ? null : client_county_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.hotel_level
     *
     * @return the value of route_order.hotel_level
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getHotel_level() {
        return hotel_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.hotel_level
     *
     * @param hotel_level the value for route_order.hotel_level
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setHotel_level(Integer hotel_level) {
        this.hotel_level = hotel_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.room_standard_count
     *
     * @return the value of route_order.room_standard_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getRoom_standard_count() {
        return room_standard_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.room_standard_count
     *
     * @param room_standard_count the value for route_order.room_standard_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setRoom_standard_count(Integer room_standard_count) {
        this.room_standard_count = room_standard_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.room_big_count
     *
     * @return the value of route_order.room_big_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getRoom_big_count() {
        return room_big_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.room_big_count
     *
     * @param room_big_count the value for route_order.room_big_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setRoom_big_count(Integer room_big_count) {
        this.room_big_count = room_big_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.room_three_count
     *
     * @return the value of route_order.room_three_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getRoom_three_count() {
        return room_three_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.room_three_count
     *
     * @param room_three_count the value for route_order.room_three_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setRoom_three_count(Integer room_three_count) {
        this.room_three_count = room_three_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.adult_count
     *
     * @return the value of route_order.adult_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getAdult_count() {
        return adult_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.adult_count
     *
     * @param adult_count the value for route_order.adult_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setAdult_count(Integer adult_count) {
        this.adult_count = adult_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.children_count
     *
     * @return the value of route_order.children_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getChildren_count() {
        return children_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.children_count
     *
     * @param children_count the value for route_order.children_count
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setChildren_count(Integer children_count) {
        this.children_count = children_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.state
     *
     * @return the value of route_order.state
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.state
     *
     * @param state the value for route_order.state
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.remarks
     *
     * @return the value of route_order.remarks
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.remarks
     *
     * @param remarks the value for route_order.remarks
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.create_time
     *
     * @return the value of route_order.create_time
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.create_time
     *
     * @param create_time the value for route_order.create_time
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.update_time
     *
     * @return the value of route_order.update_time
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.update_time
     *
     * @param update_time the value for route_order.update_time
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.creator_id
     *
     * @return the value of route_order.creator_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.creator_id
     *
     * @param creator_id the value for route_order.creator_id
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_order.creator_name
     *
     * @return the value of route_order.creator_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_order.creator_name
     *
     * @param creator_name the value for route_order.creator_name
     *
     * @mbggenerated Mon Dec 23 02:11:24 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }

    public Integer getAccompany_room_count() {
        return accompany_room_count;
    }

    public void setAccompany_room_count(Integer accompany_room_count) {
        this.accompany_room_count = accompany_room_count;
    }

    public Integer getNo_room_count() {
        return no_room_count;
    }

    public void setNo_room_count(Integer no_room_count) {
        this.no_room_count = no_room_count;
    }
}