package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteOther {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.id
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.other_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String other_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.group_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.company_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.person_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.fee_type
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private Integer fee_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.currency
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.fee
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.quantity
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.fee_total
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private BigDecimal fee_total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.remarks
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.create_time
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.update_time
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.creator_id
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_other.creator_name
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.id
     *
     * @return the value of route_other.id
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.id
     *
     * @param id the value for route_other.id
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.other_code
     *
     * @return the value of route_other.other_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getOther_code() {
        return other_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.other_code
     *
     * @param other_code the value for route_other.other_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setOther_code(String other_code) {
        this.other_code = other_code == null ? null : other_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.group_code
     *
     * @return the value of route_other.group_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.group_code
     *
     * @param group_code the value for route_other.group_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.company_code
     *
     * @return the value of route_other.company_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.company_code
     *
     * @param company_code the value for route_other.company_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.person_code
     *
     * @return the value of route_other.person_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.person_code
     *
     * @param person_code the value for route_other.person_code
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.fee_type
     *
     * @return the value of route_other.fee_type
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public Integer getFee_type() {
        return fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.fee_type
     *
     * @param fee_type the value for route_other.fee_type
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setFee_type(Integer fee_type) {
        this.fee_type = fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.currency
     *
     * @return the value of route_other.currency
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.currency
     *
     * @param currency the value for route_other.currency
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.fee
     *
     * @return the value of route_other.fee
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.fee
     *
     * @param fee the value for route_other.fee
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.quantity
     *
     * @return the value of route_other.quantity
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.quantity
     *
     * @param quantity the value for route_other.quantity
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.fee_total
     *
     * @return the value of route_other.fee_total
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public BigDecimal getFee_total() {
        return fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.fee_total
     *
     * @param fee_total the value for route_other.fee_total
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setFee_total(BigDecimal fee_total) {
        this.fee_total = fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.remarks
     *
     * @return the value of route_other.remarks
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.remarks
     *
     * @param remarks the value for route_other.remarks
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.create_time
     *
     * @return the value of route_other.create_time
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.create_time
     *
     * @param create_time the value for route_other.create_time
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.update_time
     *
     * @return the value of route_other.update_time
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.update_time
     *
     * @param update_time the value for route_other.update_time
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.creator_id
     *
     * @return the value of route_other.creator_id
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.creator_id
     *
     * @param creator_id the value for route_other.creator_id
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_other.creator_name
     *
     * @return the value of route_other.creator_name
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_other.creator_name
     *
     * @param creator_name the value for route_other.creator_name
     *
     * @mbggenerated Mon Dec 23 00:36:09 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}