package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RoutePlanBasePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.id
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.base_price_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String base_price_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.product_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String product_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.route_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String route_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.route_plan_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String route_plan_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.fee_type
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private Integer fee_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.fee_description
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String fee_description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.currency
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.price
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.quantity
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.total_price
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private BigDecimal total_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.create_time
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.update_time
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.creator_id
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_plan_base_price.creator_name
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.id
     *
     * @return the value of route_plan_base_price.id
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.id
     *
     * @param id the value for route_plan_base_price.id
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.base_price_code
     *
     * @return the value of route_plan_base_price.base_price_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getBase_price_code() {
        return base_price_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.base_price_code
     *
     * @param base_price_code the value for route_plan_base_price.base_price_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setBase_price_code(String base_price_code) {
        this.base_price_code = base_price_code == null ? null : base_price_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.product_code
     *
     * @return the value of route_plan_base_price.product_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.product_code
     *
     * @param product_code the value for route_plan_base_price.product_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.route_code
     *
     * @return the value of route_plan_base_price.route_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getRoute_code() {
        return route_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.route_code
     *
     * @param route_code the value for route_plan_base_price.route_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setRoute_code(String route_code) {
        this.route_code = route_code == null ? null : route_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.route_plan_code
     *
     * @return the value of route_plan_base_price.route_plan_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getRoute_plan_code() {
        return route_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.route_plan_code
     *
     * @param route_plan_code the value for route_plan_base_price.route_plan_code
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code == null ? null : route_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.fee_type
     *
     * @return the value of route_plan_base_price.fee_type
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public Integer getFee_type() {
        return fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.fee_type
     *
     * @param fee_type the value for route_plan_base_price.fee_type
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setFee_type(Integer fee_type) {
        this.fee_type = fee_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.fee_description
     *
     * @return the value of route_plan_base_price.fee_description
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getFee_description() {
        return fee_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.fee_description
     *
     * @param fee_description the value for route_plan_base_price.fee_description
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setFee_description(String fee_description) {
        this.fee_description = fee_description == null ? null : fee_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.currency
     *
     * @return the value of route_plan_base_price.currency
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.currency
     *
     * @param currency the value for route_plan_base_price.currency
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.price
     *
     * @return the value of route_plan_base_price.price
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.price
     *
     * @param price the value for route_plan_base_price.price
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.quantity
     *
     * @return the value of route_plan_base_price.quantity
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.quantity
     *
     * @param quantity the value for route_plan_base_price.quantity
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.total_price
     *
     * @return the value of route_plan_base_price.total_price
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public BigDecimal getTotal_price() {
        return total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.total_price
     *
     * @param total_price the value for route_plan_base_price.total_price
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setTotal_price(BigDecimal total_price) {
        this.total_price = total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.create_time
     *
     * @return the value of route_plan_base_price.create_time
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.create_time
     *
     * @param create_time the value for route_plan_base_price.create_time
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.update_time
     *
     * @return the value of route_plan_base_price.update_time
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.update_time
     *
     * @param update_time the value for route_plan_base_price.update_time
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.creator_id
     *
     * @return the value of route_plan_base_price.creator_id
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.creator_id
     *
     * @param creator_id the value for route_plan_base_price.creator_id
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_plan_base_price.creator_name
     *
     * @return the value of route_plan_base_price.creator_name
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_plan_base_price.creator_name
     *
     * @param creator_name the value for route_plan_base_price.creator_name
     *
     * @mbggenerated Sat Dec 07 14:06:19 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}