package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteInsurance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.id
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.insurance_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String insurance_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.group_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.company_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.person_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.insurance_type
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Integer insurance_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.start_date
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Date start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.end_date
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Date end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.currency
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.fee
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.insurance_count
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Integer insurance_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.fee_total
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private BigDecimal fee_total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.remarks
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.create_time
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.update_time
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.creator_id
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_insurance.creator_name
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.id
     *
     * @return the value of route_insurance.id
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.id
     *
     * @param id the value for route_insurance.id
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.insurance_code
     *
     * @return the value of route_insurance.insurance_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getInsurance_code() {
        return insurance_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.insurance_code
     *
     * @param insurance_code the value for route_insurance.insurance_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setInsurance_code(String insurance_code) {
        this.insurance_code = insurance_code == null ? null : insurance_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.group_code
     *
     * @return the value of route_insurance.group_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.group_code
     *
     * @param group_code the value for route_insurance.group_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.company_code
     *
     * @return the value of route_insurance.company_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.company_code
     *
     * @param company_code the value for route_insurance.company_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.person_code
     *
     * @return the value of route_insurance.person_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.person_code
     *
     * @param person_code the value for route_insurance.person_code
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.insurance_type
     *
     * @return the value of route_insurance.insurance_type
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Integer getInsurance_type() {
        return insurance_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.insurance_type
     *
     * @param insurance_type the value for route_insurance.insurance_type
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setInsurance_type(Integer insurance_type) {
        this.insurance_type = insurance_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.start_date
     *
     * @return the value of route_insurance.start_date
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Date getStart_date() {
        return start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.start_date
     *
     * @param start_date the value for route_insurance.start_date
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.end_date
     *
     * @return the value of route_insurance.end_date
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Date getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.end_date
     *
     * @param end_date the value for route_insurance.end_date
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setEnd_date(Date end_date) {
        this.end_date = end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.currency
     *
     * @return the value of route_insurance.currency
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.currency
     *
     * @param currency the value for route_insurance.currency
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.fee
     *
     * @return the value of route_insurance.fee
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.fee
     *
     * @param fee the value for route_insurance.fee
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.insurance_count
     *
     * @return the value of route_insurance.insurance_count
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Integer getInsurance_count() {
        return insurance_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.insurance_count
     *
     * @param insurance_count the value for route_insurance.insurance_count
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setInsurance_count(Integer insurance_count) {
        this.insurance_count = insurance_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.fee_total
     *
     * @return the value of route_insurance.fee_total
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public BigDecimal getFee_total() {
        return fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.fee_total
     *
     * @param fee_total the value for route_insurance.fee_total
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setFee_total(BigDecimal fee_total) {
        this.fee_total = fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.remarks
     *
     * @return the value of route_insurance.remarks
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.remarks
     *
     * @param remarks the value for route_insurance.remarks
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.create_time
     *
     * @return the value of route_insurance.create_time
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.create_time
     *
     * @param create_time the value for route_insurance.create_time
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.update_time
     *
     * @return the value of route_insurance.update_time
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.update_time
     *
     * @param update_time the value for route_insurance.update_time
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.creator_id
     *
     * @return the value of route_insurance.creator_id
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.creator_id
     *
     * @param creator_id the value for route_insurance.creator_id
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_insurance.creator_name
     *
     * @return the value of route_insurance.creator_name
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_insurance.creator_name
     *
     * @param creator_name the value for route_insurance.creator_name
     *
     * @mbggenerated Sun Dec 22 23:32:07 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}