package com.kunlun.erp.core.entity;

import java.util.Date;

public class RoutePricePlan {

    private Integer id;

    private String price_plan_code;

    private String product_code;

    private String route_plan_code;

    private String price_plan_name;

    private Date create_time;

    private Date update_time;

    private Integer creator_id;

    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.id
     *
     * @return the value of route_price_plan.id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.id
     *
     * @param id the value for route_price_plan.id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.price_plan_code
     *
     * @return the value of route_price_plan.price_plan_code
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public String getPrice_plan_code() {
        return price_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.price_plan_code
     *
     * @param price_plan_code the value for route_price_plan.price_plan_code
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setPrice_plan_code(String price_plan_code) {
        this.price_plan_code = price_plan_code == null ? null : price_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.price_plan_name
     *
     * @return the value of route_price_plan.price_plan_name
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public String getPrice_plan_name() {
        return price_plan_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.price_plan_name
     *
     * @param price_plan_name the value for route_price_plan.price_plan_name
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setPrice_plan_name(String price_plan_name) {
        this.price_plan_name = price_plan_name == null ? null : price_plan_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.create_time
     *
     * @return the value of route_price_plan.create_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.create_time
     *
     * @param create_time the value for route_price_plan.create_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.update_time
     *
     * @return the value of route_price_plan.update_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.update_time
     *
     * @param update_time the value for route_price_plan.update_time
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.creator_id
     *
     * @return the value of route_price_plan.creator_id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.creator_id
     *
     * @param creator_id the value for route_price_plan.creator_id
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan.creator_name
     *
     * @return the value of route_price_plan.creator_name
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan.creator_name
     *
     * @param creator_name the value for route_price_plan.creator_name
     *
     * @mbggenerated Mon Dec 16 16:56:12 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }

    public String getProduct_code() {
        return product_code;
    }

    public void setProduct_code(String product_code) {
        this.product_code = product_code;
    }

    public String getRoute_plan_code() {
        return route_plan_code;
    }

    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code;
    }
}