package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RoutePricePlanCostDetail {

    private Integer id;

    private String cost_code;

    private String product_code;


    private String route_code;


    private String route_plan_code;


    private String price_code;

    private String price_plan_code;


    private Date departure_date;


    private Integer cost_type;


    private String cost_description;


    private String currency;


    private BigDecimal cost_price;


    private Integer quantity;


    private BigDecimal total_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_price_plan_cost_detail.create_time
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_price_plan_cost_detail.update_time
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_price_plan_cost_detail.creator_id
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_price_plan_cost_detail.creator_name
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.id
     *
     * @return the value of route_price_plan_cost_detail.id
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.id
     *
     * @param id the value for route_price_plan_cost_detail.id
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.cost_code
     *
     * @return the value of route_price_plan_cost_detail.cost_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getCost_code() {
        return cost_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.cost_code
     *
     * @param cost_code the value for route_price_plan_cost_detail.cost_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCost_code(String cost_code) {
        this.cost_code = cost_code == null ? null : cost_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.product_code
     *
     * @return the value of route_price_plan_cost_detail.product_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getProduct_code() {
        return product_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.product_code
     *
     * @param product_code the value for route_price_plan_cost_detail.product_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setProduct_code(String product_code) {
        this.product_code = product_code == null ? null : product_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.route_code
     *
     * @return the value of route_price_plan_cost_detail.route_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getRoute_code() {
        return route_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.route_code
     *
     * @param route_code the value for route_price_plan_cost_detail.route_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setRoute_code(String route_code) {
        this.route_code = route_code == null ? null : route_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.route_plan_code
     *
     * @return the value of route_price_plan_cost_detail.route_plan_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getRoute_plan_code() {
        return route_plan_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.route_plan_code
     *
     * @param route_plan_code the value for route_price_plan_cost_detail.route_plan_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setRoute_plan_code(String route_plan_code) {
        this.route_plan_code = route_plan_code == null ? null : route_plan_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.price_code
     *
     * @return the value of route_price_plan_cost_detail.price_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getPrice_code() {
        return price_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.price_code
     *
     * @param price_code the value for route_price_plan_cost_detail.price_code
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setPrice_code(String price_code) {
        this.price_code = price_code == null ? null : price_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.departure_date
     *
     * @return the value of route_price_plan_cost_detail.departure_date
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Date getDeparture_date() {
        return departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.departure_date
     *
     * @param departure_date the value for route_price_plan_cost_detail.departure_date
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setDeparture_date(Date departure_date) {
        this.departure_date = departure_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.cost_type
     *
     * @return the value of route_price_plan_cost_detail.cost_type
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Integer getCost_type() {
        return cost_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.cost_type
     *
     * @param cost_type the value for route_price_plan_cost_detail.cost_type
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCost_type(Integer cost_type) {
        this.cost_type = cost_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.cost_description
     *
     * @return the value of route_price_plan_cost_detail.cost_description
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getCost_description() {
        return cost_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.cost_description
     *
     * @param cost_description the value for route_price_plan_cost_detail.cost_description
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCost_description(String cost_description) {
        this.cost_description = cost_description == null ? null : cost_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.currency
     *
     * @return the value of route_price_plan_cost_detail.currency
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.currency
     *
     * @param currency the value for route_price_plan_cost_detail.currency
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.cost_price
     *
     * @return the value of route_price_plan_cost_detail.cost_price
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public BigDecimal getCost_price() {
        return cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.cost_price
     *
     * @param cost_price the value for route_price_plan_cost_detail.cost_price
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCost_price(BigDecimal cost_price) {
        this.cost_price = cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.quantity
     *
     * @return the value of route_price_plan_cost_detail.quantity
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.quantity
     *
     * @param quantity the value for route_price_plan_cost_detail.quantity
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.total_price
     *
     * @return the value of route_price_plan_cost_detail.total_price
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public BigDecimal getTotal_price() {
        return total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.total_price
     *
     * @param total_price the value for route_price_plan_cost_detail.total_price
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setTotal_price(BigDecimal total_price) {
        this.total_price = total_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.create_time
     *
     * @return the value of route_price_plan_cost_detail.create_time
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.create_time
     *
     * @param create_time the value for route_price_plan_cost_detail.create_time
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.update_time
     *
     * @return the value of route_price_plan_cost_detail.update_time
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.update_time
     *
     * @param update_time the value for route_price_plan_cost_detail.update_time
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.creator_id
     *
     * @return the value of route_price_plan_cost_detail.creator_id
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.creator_id
     *
     * @param creator_id the value for route_price_plan_cost_detail.creator_id
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_price_plan_cost_detail.creator_name
     *
     * @return the value of route_price_plan_cost_detail.creator_name
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_price_plan_cost_detail.creator_name
     *
     * @param creator_name the value for route_price_plan_cost_detail.creator_name
     *
     * @mbggenerated Tue Dec 17 09:21:23 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }

    public String getPrice_plan_code() {
        return price_plan_code;
    }

    public void setPrice_plan_code(String price_plan_code) {
        this.price_plan_code = price_plan_code;
    }
}