package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RouteTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.id
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.ticket_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String ticket_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.group_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String group_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.company_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.person_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String person_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.ticket_type
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Integer ticket_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.ticket_date
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Date ticket_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.currency
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.fee
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.ticket_count
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Integer ticket_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.fee_total
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private BigDecimal fee_total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.remarks
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.create_time
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.update_time
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.creator_id
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_ticket.creator_name
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    private String creator_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.id
     *
     * @return the value of route_ticket.id
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.id
     *
     * @param id the value for route_ticket.id
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.ticket_code
     *
     * @return the value of route_ticket.ticket_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getTicket_code() {
        return ticket_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.ticket_code
     *
     * @param ticket_code the value for route_ticket.ticket_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setTicket_code(String ticket_code) {
        this.ticket_code = ticket_code == null ? null : ticket_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.group_code
     *
     * @return the value of route_ticket.group_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.group_code
     *
     * @param group_code the value for route_ticket.group_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.company_code
     *
     * @return the value of route_ticket.company_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getCompany_code() {
        return company_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.company_code
     *
     * @param company_code the value for route_ticket.company_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setCompany_code(String company_code) {
        this.company_code = company_code == null ? null : company_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.person_code
     *
     * @return the value of route_ticket.person_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getPerson_code() {
        return person_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.person_code
     *
     * @param person_code the value for route_ticket.person_code
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setPerson_code(String person_code) {
        this.person_code = person_code == null ? null : person_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.ticket_type
     *
     * @return the value of route_ticket.ticket_type
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Integer getTicket_type() {
        return ticket_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.ticket_type
     *
     * @param ticket_type the value for route_ticket.ticket_type
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setTicket_type(Integer ticket_type) {
        this.ticket_type = ticket_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.ticket_date
     *
     * @return the value of route_ticket.ticket_date
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Date getTicket_date() {
        return ticket_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.ticket_date
     *
     * @param ticket_date the value for route_ticket.ticket_date
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setTicket_date(Date ticket_date) {
        this.ticket_date = ticket_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.currency
     *
     * @return the value of route_ticket.currency
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.currency
     *
     * @param currency the value for route_ticket.currency
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.fee
     *
     * @return the value of route_ticket.fee
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.fee
     *
     * @param fee the value for route_ticket.fee
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.ticket_count
     *
     * @return the value of route_ticket.ticket_count
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Integer getTicket_count() {
        return ticket_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.ticket_count
     *
     * @param ticket_count the value for route_ticket.ticket_count
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setTicket_count(Integer ticket_count) {
        this.ticket_count = ticket_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.fee_total
     *
     * @return the value of route_ticket.fee_total
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public BigDecimal getFee_total() {
        return fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.fee_total
     *
     * @param fee_total the value for route_ticket.fee_total
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setFee_total(BigDecimal fee_total) {
        this.fee_total = fee_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.remarks
     *
     * @return the value of route_ticket.remarks
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.remarks
     *
     * @param remarks the value for route_ticket.remarks
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.create_time
     *
     * @return the value of route_ticket.create_time
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.create_time
     *
     * @param create_time the value for route_ticket.create_time
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.update_time
     *
     * @return the value of route_ticket.update_time
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.update_time
     *
     * @param update_time the value for route_ticket.update_time
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.creator_id
     *
     * @return the value of route_ticket.creator_id
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.creator_id
     *
     * @param creator_id the value for route_ticket.creator_id
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route_ticket.creator_name
     *
     * @return the value of route_ticket.creator_name
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route_ticket.creator_name
     *
     * @param creator_name the value for route_ticket.creator_name
     *
     * @mbggenerated Fri Dec 20 17:45:34 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }
}