package com.kunlun.erp.core.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SalesChannelCost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.cost_code
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private String cost_code;

    private String company_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.cost_type_id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private Integer cost_type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.product_category_code
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private String product_category_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.cost_settlement_mode
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private Integer cost_settlement_mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.charge_mode
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private Integer charge_mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.fee
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.rate
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.create_time
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.creator_id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private Integer creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_channel_cost.creator_name
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    private String creator_name;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_channel_cost
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public SalesChannelCost() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.id
     *
     * @return the value of sales_channel_cost.id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.id
     *
     * @param id the value for sales_channel_cost.id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.cost_code
     *
     * @return the value of sales_channel_cost.cost_code
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public String getCost_code() {
        return cost_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.cost_code
     *
     * @param cost_code the value for sales_channel_cost.cost_code
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCost_code(String cost_code) {
        this.cost_code = cost_code == null ? null : cost_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.cost_type_id
     *
     * @return the value of sales_channel_cost.cost_type_id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public Integer getCost_type_id() {
        return cost_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.cost_type_id
     *
     * @param cost_type_id the value for sales_channel_cost.cost_type_id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCost_type_id(Integer cost_type_id) {
        this.cost_type_id = cost_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.product_category_code
     *
     * @return the value of sales_channel_cost.product_category_code
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public String getProduct_category_code() {
        return product_category_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.product_category_code
     *
     * @param product_category_code the value for sales_channel_cost.product_category_code
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setProduct_category_code(String product_category_code) {
        this.product_category_code = product_category_code == null ? null : product_category_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.cost_settlement_mode
     *
     * @return the value of sales_channel_cost.cost_settlement_mode
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public Integer getCost_settlement_mode() {
        return cost_settlement_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.cost_settlement_mode
     *
     * @param cost_settlement_mode the value for sales_channel_cost.cost_settlement_mode
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCost_settlement_mode(Integer cost_settlement_mode) {
        this.cost_settlement_mode = cost_settlement_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.charge_mode
     *
     * @return the value of sales_channel_cost.charge_mode
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public Integer getCharge_mode() {
        return charge_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.charge_mode
     *
     * @param charge_mode the value for sales_channel_cost.charge_mode
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCharge_mode(Integer charge_mode) {
        this.charge_mode = charge_mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.fee
     *
     * @return the value of sales_channel_cost.fee
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.fee
     *
     * @param fee the value for sales_channel_cost.fee
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.rate
     *
     * @return the value of sales_channel_cost.rate
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.rate
     *
     * @param rate the value for sales_channel_cost.rate
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.create_time
     *
     * @return the value of sales_channel_cost.create_time
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.create_time
     *
     * @param create_time the value for sales_channel_cost.create_time
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.creator_id
     *
     * @return the value of sales_channel_cost.creator_id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.creator_id
     *
     * @param creator_id the value for sales_channel_cost.creator_id
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_channel_cost.creator_name
     *
     * @return the value of sales_channel_cost.creator_name
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public String getCreator_name() {
        return creator_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_channel_cost.creator_name
     *
     * @param creator_name the value for sales_channel_cost.creator_name
     *
     * @mbggenerated Wed Dec 04 17:03:29 CST 2019
     */
    public void setCreator_name(String creator_name) {
        this.creator_name = creator_name == null ? null : creator_name.trim();
    }

    public String getCompany_code() {
        return company_code;
    }

    public void setCompany_code(String company_code) {
        this.company_code = company_code;
    }
}