package com.kunlun.erp.core.entity;

import java.util.Date;

public class SysCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.country_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer country_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.province_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer province_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String zh_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String en_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String first_letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.longitude
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.latitude
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String attractions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.is_capital
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer is_capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.is_hot
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer is_hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.grade
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.district_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer district_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.type
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.like_count
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer like_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String create_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.update_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.update_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String update_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.ly_city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer ly_city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.map_img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String map_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.img_list
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String img_list;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_city.description
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysCity(Integer city_id, Integer country_id, Integer province_id, String zh_name, String en_name, String first_letter, String longitude, String latitude, String img, String attractions, Integer is_capital, Integer is_hot, Integer grade, Integer district_id, Integer order_id, Integer type, Integer state, Integer like_count, Date create_time, String create_person, Date update_time, String update_person, Integer ly_city_id, String map_img, String img_list, String description) {
        this.city_id = city_id;
        this.country_id = country_id;
        this.province_id = province_id;
        this.zh_name = zh_name;
        this.en_name = en_name;
        this.first_letter = first_letter;
        this.longitude = longitude;
        this.latitude = latitude;
        this.img = img;
        this.attractions = attractions;
        this.is_capital = is_capital;
        this.is_hot = is_hot;
        this.grade = grade;
        this.district_id = district_id;
        this.order_id = order_id;
        this.type = type;
        this.state = state;
        this.like_count = like_count;
        this.create_time = create_time;
        this.create_person = create_person;
        this.update_time = update_time;
        this.update_person = update_person;
        this.ly_city_id = ly_city_id;
        this.map_img = map_img;
        this.img_list = img_list;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_city
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysCity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.city_id
     *
     * @return the value of sys_city.city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.city_id
     *
     * @param city_id the value for sys_city.city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.country_id
     *
     * @return the value of sys_city.country_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getCountry_id() {
        return country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.country_id
     *
     * @param country_id the value for sys_city.country_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCountry_id(Integer country_id) {
        this.country_id = country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.province_id
     *
     * @return the value of sys_city.province_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getProvince_id() {
        return province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.province_id
     *
     * @param province_id the value for sys_city.province_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.zh_name
     *
     * @return the value of sys_city.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getZh_name() {
        return zh_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.zh_name
     *
     * @param zh_name the value for sys_city.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setZh_name(String zh_name) {
        this.zh_name = zh_name == null ? null : zh_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.en_name
     *
     * @return the value of sys_city.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getEn_name() {
        return en_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.en_name
     *
     * @param en_name the value for sys_city.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setEn_name(String en_name) {
        this.en_name = en_name == null ? null : en_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.first_letter
     *
     * @return the value of sys_city.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getFirst_letter() {
        return first_letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.first_letter
     *
     * @param first_letter the value for sys_city.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setFirst_letter(String first_letter) {
        this.first_letter = first_letter == null ? null : first_letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.longitude
     *
     * @return the value of sys_city.longitude
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.longitude
     *
     * @param longitude the value for sys_city.longitude
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.latitude
     *
     * @return the value of sys_city.latitude
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.latitude
     *
     * @param latitude the value for sys_city.latitude
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.img
     *
     * @return the value of sys_city.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.img
     *
     * @param img the value for sys_city.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.attractions
     *
     * @return the value of sys_city.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getAttractions() {
        return attractions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.attractions
     *
     * @param attractions the value for sys_city.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setAttractions(String attractions) {
        this.attractions = attractions == null ? null : attractions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.is_capital
     *
     * @return the value of sys_city.is_capital
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getIs_capital() {
        return is_capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.is_capital
     *
     * @param is_capital the value for sys_city.is_capital
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setIs_capital(Integer is_capital) {
        this.is_capital = is_capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.is_hot
     *
     * @return the value of sys_city.is_hot
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getIs_hot() {
        return is_hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.is_hot
     *
     * @param is_hot the value for sys_city.is_hot
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setIs_hot(Integer is_hot) {
        this.is_hot = is_hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.grade
     *
     * @return the value of sys_city.grade
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.grade
     *
     * @param grade the value for sys_city.grade
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.district_id
     *
     * @return the value of sys_city.district_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getDistrict_id() {
        return district_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.district_id
     *
     * @param district_id the value for sys_city.district_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setDistrict_id(Integer district_id) {
        this.district_id = district_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.order_id
     *
     * @return the value of sys_city.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.order_id
     *
     * @param order_id the value for sys_city.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.type
     *
     * @return the value of sys_city.type
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.type
     *
     * @param type the value for sys_city.type
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.state
     *
     * @return the value of sys_city.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.state
     *
     * @param state the value for sys_city.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.like_count
     *
     * @return the value of sys_city.like_count
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getLike_count() {
        return like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.like_count
     *
     * @param like_count the value for sys_city.like_count
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setLike_count(Integer like_count) {
        this.like_count = like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.create_time
     *
     * @return the value of sys_city.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.create_time
     *
     * @param create_time the value for sys_city.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.create_person
     *
     * @return the value of sys_city.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getCreate_person() {
        return create_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.create_person
     *
     * @param create_person the value for sys_city.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_person(String create_person) {
        this.create_person = create_person == null ? null : create_person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.update_time
     *
     * @return the value of sys_city.update_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.update_time
     *
     * @param update_time the value for sys_city.update_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.update_person
     *
     * @return the value of sys_city.update_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getUpdate_person() {
        return update_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.update_person
     *
     * @param update_person the value for sys_city.update_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setUpdate_person(String update_person) {
        this.update_person = update_person == null ? null : update_person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.ly_city_id
     *
     * @return the value of sys_city.ly_city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getLy_city_id() {
        return ly_city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.ly_city_id
     *
     * @param ly_city_id the value for sys_city.ly_city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setLy_city_id(Integer ly_city_id) {
        this.ly_city_id = ly_city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.map_img
     *
     * @return the value of sys_city.map_img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getMap_img() {
        return map_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.map_img
     *
     * @param map_img the value for sys_city.map_img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setMap_img(String map_img) {
        this.map_img = map_img == null ? null : map_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.img_list
     *
     * @return the value of sys_city.img_list
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getImg_list() {
        return img_list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.img_list
     *
     * @param img_list the value for sys_city.img_list
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setImg_list(String img_list) {
        this.img_list = img_list == null ? null : img_list.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_city.description
     *
     * @return the value of sys_city.description
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_city.description
     *
     * @param description the value for sys_city.description
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}