package com.kunlun.erp.core.entity;

import java.util.Date;

public class SysCountry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.country_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer country_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String zh_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String en_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.js_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String js_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String first_letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String attractions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String create_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_country.creator_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer creator_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_country
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysCountry(Integer country_id, String zh_name, String en_name, String js_name, String first_letter, String img, String attractions, Integer state, Date create_time, String create_person, Integer creator_id) {
        this.country_id = country_id;
        this.zh_name = zh_name;
        this.en_name = en_name;
        this.js_name = js_name;
        this.first_letter = first_letter;
        this.img = img;
        this.attractions = attractions;
        this.state = state;
        this.create_time = create_time;
        this.create_person = create_person;
        this.creator_id = creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_country
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysCountry() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.country_id
     *
     * @return the value of sys_country.country_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getCountry_id() {
        return country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.country_id
     *
     * @param country_id the value for sys_country.country_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCountry_id(Integer country_id) {
        this.country_id = country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.zh_name
     *
     * @return the value of sys_country.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getZh_name() {
        return zh_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.zh_name
     *
     * @param zh_name the value for sys_country.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setZh_name(String zh_name) {
        this.zh_name = zh_name == null ? null : zh_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.en_name
     *
     * @return the value of sys_country.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getEn_name() {
        return en_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.en_name
     *
     * @param en_name the value for sys_country.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setEn_name(String en_name) {
        this.en_name = en_name == null ? null : en_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.js_name
     *
     * @return the value of sys_country.js_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getJs_name() {
        return js_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.js_name
     *
     * @param js_name the value for sys_country.js_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setJs_name(String js_name) {
        this.js_name = js_name == null ? null : js_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.first_letter
     *
     * @return the value of sys_country.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getFirst_letter() {
        return first_letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.first_letter
     *
     * @param first_letter the value for sys_country.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setFirst_letter(String first_letter) {
        this.first_letter = first_letter == null ? null : first_letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.img
     *
     * @return the value of sys_country.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.img
     *
     * @param img the value for sys_country.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.attractions
     *
     * @return the value of sys_country.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getAttractions() {
        return attractions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.attractions
     *
     * @param attractions the value for sys_country.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setAttractions(String attractions) {
        this.attractions = attractions == null ? null : attractions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.state
     *
     * @return the value of sys_country.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.state
     *
     * @param state the value for sys_country.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.create_time
     *
     * @return the value of sys_country.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.create_time
     *
     * @param create_time the value for sys_country.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.create_person
     *
     * @return the value of sys_country.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getCreate_person() {
        return create_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.create_person
     *
     * @param create_person the value for sys_country.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_person(String create_person) {
        this.create_person = create_person == null ? null : create_person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_country.creator_id
     *
     * @return the value of sys_country.creator_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getCreator_id() {
        return creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_country.creator_id
     *
     * @param creator_id the value for sys_country.creator_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreator_id(Integer creator_id) {
        this.creator_id = creator_id;
    }
}