package com.kunlun.erp.core.entity;

import java.util.Date;

public class SysCounty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.county_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer county_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer city_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String zh_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String en_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String first_letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String create_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.update_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_county.update_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String update_person;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysCounty(Integer county_id, Integer city_id, String zh_name, String en_name, String first_letter, Integer order_id, Integer state, Date create_time, String create_person, Date update_time, String update_person) {
        this.county_id = county_id;
        this.city_id = city_id;
        this.zh_name = zh_name;
        this.en_name = en_name;
        this.first_letter = first_letter;
        this.order_id = order_id;
        this.state = state;
        this.create_time = create_time;
        this.create_person = create_person;
        this.update_time = update_time;
        this.update_person = update_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_county
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysCounty() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.county_id
     *
     * @return the value of sys_county.county_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getCounty_id() {
        return county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.county_id
     *
     * @param county_id the value for sys_county.county_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCounty_id(Integer county_id) {
        this.county_id = county_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.city_id
     *
     * @return the value of sys_county.city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.city_id
     *
     * @param city_id the value for sys_county.city_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.zh_name
     *
     * @return the value of sys_county.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getZh_name() {
        return zh_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.zh_name
     *
     * @param zh_name the value for sys_county.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setZh_name(String zh_name) {
        this.zh_name = zh_name == null ? null : zh_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.en_name
     *
     * @return the value of sys_county.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getEn_name() {
        return en_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.en_name
     *
     * @param en_name the value for sys_county.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setEn_name(String en_name) {
        this.en_name = en_name == null ? null : en_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.first_letter
     *
     * @return the value of sys_county.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getFirst_letter() {
        return first_letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.first_letter
     *
     * @param first_letter the value for sys_county.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setFirst_letter(String first_letter) {
        this.first_letter = first_letter == null ? null : first_letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.order_id
     *
     * @return the value of sys_county.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.order_id
     *
     * @param order_id the value for sys_county.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.state
     *
     * @return the value of sys_county.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.state
     *
     * @param state the value for sys_county.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.create_time
     *
     * @return the value of sys_county.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.create_time
     *
     * @param create_time the value for sys_county.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.create_person
     *
     * @return the value of sys_county.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getCreate_person() {
        return create_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.create_person
     *
     * @param create_person the value for sys_county.create_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_person(String create_person) {
        this.create_person = create_person == null ? null : create_person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.update_time
     *
     * @return the value of sys_county.update_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.update_time
     *
     * @param update_time the value for sys_county.update_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_county.update_person
     *
     * @return the value of sys_county.update_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getUpdate_person() {
        return update_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_county.update_person
     *
     * @param update_person the value for sys_county.update_person
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setUpdate_person(String update_person) {
        this.update_person = update_person == null ? null : update_person.trim();
    }
}