package com.kunlun.erp.core.entity;

import java.util.Date;

public class SysProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.province_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer province_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String zh_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String en_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String first_letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.district_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer district_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private String attractions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_province.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysProvince(Integer province_id, String zh_name, String en_name, String first_letter, Integer district_id, Integer order_id, String img, String attractions, Integer state, Date create_time) {
        this.province_id = province_id;
        this.zh_name = zh_name;
        this.en_name = en_name;
        this.first_letter = first_letter;
        this.district_id = district_id;
        this.order_id = order_id;
        this.img = img;
        this.attractions = attractions;
        this.state = state;
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_province
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public SysProvince() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.province_id
     *
     * @return the value of sys_province.province_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getProvince_id() {
        return province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.province_id
     *
     * @param province_id the value for sys_province.province_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setProvince_id(Integer province_id) {
        this.province_id = province_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.zh_name
     *
     * @return the value of sys_province.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getZh_name() {
        return zh_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.zh_name
     *
     * @param zh_name the value for sys_province.zh_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setZh_name(String zh_name) {
        this.zh_name = zh_name == null ? null : zh_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.en_name
     *
     * @return the value of sys_province.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getEn_name() {
        return en_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.en_name
     *
     * @param en_name the value for sys_province.en_name
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setEn_name(String en_name) {
        this.en_name = en_name == null ? null : en_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.first_letter
     *
     * @return the value of sys_province.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getFirst_letter() {
        return first_letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.first_letter
     *
     * @param first_letter the value for sys_province.first_letter
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setFirst_letter(String first_letter) {
        this.first_letter = first_letter == null ? null : first_letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.district_id
     *
     * @return the value of sys_province.district_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getDistrict_id() {
        return district_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.district_id
     *
     * @param district_id the value for sys_province.district_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setDistrict_id(Integer district_id) {
        this.district_id = district_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.order_id
     *
     * @return the value of sys_province.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.order_id
     *
     * @param order_id the value for sys_province.order_id
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.img
     *
     * @return the value of sys_province.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.img
     *
     * @param img the value for sys_province.img
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.attractions
     *
     * @return the value of sys_province.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public String getAttractions() {
        return attractions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.attractions
     *
     * @param attractions the value for sys_province.attractions
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setAttractions(String attractions) {
        this.attractions = attractions == null ? null : attractions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.state
     *
     * @return the value of sys_province.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.state
     *
     * @param state the value for sys_province.state
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_province.create_time
     *
     * @return the value of sys_province.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_province.create_time
     *
     * @param create_time the value for sys_province.create_time
     *
     * @mbggenerated Mon Nov 25 12:16:32 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}