package com.kunlun.erp.core.mapper;

import com.kunlun.erp.core.entity.GroupCode;

public interface GroupCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    int insert(GroupCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    int insertSelective(GroupCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    GroupCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    int updateByPrimaryKeySelective(GroupCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_code
     *
     * @mbggenerated Mon Jan 13 10:56:08 CST 2020
     */
    int updateByPrimaryKey(GroupCode record);
}